# ==============================================================================
# BeaconLink
# .golangci.yml
#
# Documentation:
# https://golangci-lint.run/
# ==============================================================================

run:
  timeout: 5m

output:
  formats:
    text:
      path: stdout
      colors: true

linters:
  default: none

  enable:
    # --------------------------------------------------------------------------
    # Correctness
    # --------------------------------------------------------------------------
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple

    # --------------------------------------------------------------------------
    # Code Quality
    # --------------------------------------------------------------------------
    - revive
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - exhaustive
    - gocritic
    - misspell
    - nilerr
    - noctx
    - predeclared
    - reassign
    - sqlclosecheck
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

    # --------------------------------------------------------------------------
    # Complexity
    # --------------------------------------------------------------------------
    - cyclop
    - gocognit
    - nestif

    # --------------------------------------------------------------------------
    # Style
    # --------------------------------------------------------------------------
    - asciicheck
    - bidichk
    - decorder
    - dogsled
    - errname
    - goconst
    - godot
    - gofmt
    - goimports
    - intrange
    - lll
    - nilnil
    - nolintlint
    - perfsprint
    - tagliatelle
    - testpackage
    - thelper
    - usetesting

formatters:
  enable:
    - gofmt
    - goimports

settings:
  cyclop:
    max-complexity: 20

  gocognit:
    min-complexity: 20

  lll:
    line-length: 120

  misspell:
    locale: US

  revive:
    confidence: 0.8

    rules:
      - name: exported
      - name: package-comments
      - name: indent-error-flow
      - name: var-naming
      - name: error-return
      - name: error-strings
      - name: receiver-naming
      - name: empty-block
      - name: superfluous-else
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter

  goimports:
    local-prefixes:
      - github.com/vishwanathdvgmm/beaconlink

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error

exclusions:
  generated: strict

  paths:
    - vendor
    - third_party
    - testdata
    - web
    - dist
    - bin

  rules:
    - path: '.*\.pb\.go'
      linters:
        - all

    - path: '.*_string\.go'
      linters:
        - all

    - path: '.*mock.*\.go'
      linters:
        - all

    - path: '.*_test\.go'
      linters:
        - cyclop
        - gocognit
        - nestif
        - lll

    - path: "^examples/"
      linters:
        - revive
        - lll
